using System.IO;
using UnityEditor;
using UnityEngine;

namespace Game.Editor
{
    public static class LayersAutoGeneration
    {
        private const string FolderPath = "!/Source/AutoGenerated/";
        private const string Namespace = "Game.AutoGenerated";
        private const string FileName = "Layers";

        private static string FullPath
        {
            get { return Path.Combine(Application.dataPath, FolderPath); }
        }

        [MenuItem("Tools/Generate Layers")]
        private static void GenerateLayers()
        {
            if (!Directory.Exists(FullPath))
                Directory.CreateDirectory(FullPath);

            File.WriteAllText(FullPath + $"{FileName}.cs", GenerateLayersFile());
            AssetDatabase.Refresh();
        }

        private static string GenerateLayersFile()
        {
            string[] layerNames = UnityEditorInternal.InternalEditorUtility.layers;

            return $@"
namespace {Namespace}
{{
    public static class Layers
    {{
{GenerateLayerConstants(layerNames)}
    }}
}}
";
        }

        private static string GenerateLayerConstants(string[] layerNames)
        {
            string layerConstants = "";
            foreach (string layerName in layerNames)
            {
                layerConstants += $"\t\tpublic const string {layerName.Replace(" ", "")} = \"{layerName}\";\n";
            }

            return layerConstants;
        }
    }
}