
namespace Game.AutoGenerated
{
    public static class Layers
    {
		public const string Default = "Default";
		public const string TransparentFX = "TransparentFX";
		public const string IgnoreRaycast = "Ignore Raycast";
		public const string Water = "Water";
		public const string UI = "UI";
		public const string Player = "Player";
		public const string CollidePlayer = "CollidePlayer";

    }
}
